name: Weekly Stats Report

on:
  pull_request:
    types:
      - closed

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Open PR Data
        id: extract-prs
        run: |
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed")
          
          echo "$PRS" | jq '.' > pr_data.json
          echo "PR_DATA=pr_data.json" >> $GITHUB_ENV

      - name: Upload pr data
        uses: actions/upload-artifact@v4
        with:
          name: pr-data
          path: pr-data.json

      - name: Analyze PRs and Generate Stats
        id: generate-stats
        run: |
          python .github/workflows/generate_weekly_stats.py pr_data.json weekly_stats.json

      - name: Post Weekly Stats
        run: |
          CONTENT=$(cat weekly_stats.json)
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "n주차 정산", "body": "'"$CONTENT"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues"
      
      - name: Upload weekly stats
        uses: actions/upload-artifact@v4
        with:
          name: weekly-stats
          path: weekly_stats.json
