name: Auto Create Pull Request

on:
  push:
    branches:
      - 'hjk0761'
      - 'test'

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: summrize
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          pr_title="${{ env.BRANCH_NAME }}"
          echo "PR_TITLE=$pr_title" >> $GITHUB_ENV
          summary=$(cat body.md)
            echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$summary" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        run: |
          gh pr create --title "${{ env.PR_TITLE }}" --body "${{ env.PR_BODY }}" --base "main"
        env:
          GH_TOKEN: ${{ github.token }}
