name: Test Schedule Workflow
on:
  schedule:
    - cron: '*/2 * * * *' # 5분 간격으로 테스트

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "Workflow triggered at $(date)"
